name: pic_dart_emu
description: A PIC emulator with Dart 
# version: 1.0.0
# homepage: https://bmantoni.github.io

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
#  path: ^1.6.0
  args: ^1.5.3

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
